# Define your own shop routes here

#webgriffe_sylius_meilisearch_example:
#    path: /example
#    defaults:
#        _controller: Webgriffe\SyliusMeilisearchPlugin\Controller\ExampleController::exampleAction
#        name: ~
